### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/concise-print#1]
Extracted from the core:

```scss
//
// Print
// =============================================================================

@media print {
  @page {
    margin: .5cm;
  }

  *,
  *:before,
  *:after {
    background: transparent !important;
    color: black !important;
    filter: none !important;
    text-shadow: none !important;
  }

  :root {
    background-color: white;
    color: black;
    font: 11pt / $line-height-print $font-family-print;
  }

  img {
    max-width: 100% !important;
    page-break-after: avoid;
    page-break-inside: avoid;
  }

  video,
  audio,
  object,
  embed,
  nav,
  footer,
  a[href^="#"]:after {
    display: none;
    visibility: hidden;
  }

  p,
  h2, h3 {
    orphans: 3;
    widows: 3;
  }

  h2, h3 {
    page-break-after: avoid;
  }

  a,
  a:visited {
    color: black;
    font-size: .57em;
    text-decoration: underline;
    word-wrap: break-word;

    &[href]:after {
      content: " (" attr(href) ")";
      font-size: smaller;
    }
  }

  q:after {
    content: " (Source: " attr(cite) ")";
  }

  abbr[title]:after {
    content: " (" attr(title) ")";
  }

  a {
    &:after,
    &[href^="javascript:"]:after,
    &[href^="#"]:after {
      content: "";
    }
  }

  pre,
  code {
    background-color: transparent;
    border: 1px solid getColor(base, border);
    page-break-inside: avoid;
  }

  blockquote {
    border: none;
    page-break-inside: avoid;
  }

  thead {
    display: table-header-group;
  }

  tr,
  img {
    page-break-inside: avoid;
  }

  ol {
    padding-left: 1.25em;
  }

  ul {
    padding-left: 0;
    list-style: none;

    ul,
    ul ul {
      padding-left: 1.5em;
    }
  }

  ul,
  ol {
    li {
      content: "&raquo; ";
    }
  }

  @media (min-width: $bp-extra-small) {
    table {
      page-break-inside: avoid;
      width: 100% !important;

      th,
      td {
        line-height: unitSize(5) !important;
      }
    }
  }
}
```
